# Generated by Django 4.2.7 on 2025-11-19 12:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_email_verified_user_token_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="verification_token",
            field=models.UUIDField(
                db_column="email_verification_token",
                default=uuid.uuid4,
                editable=False,
                unique=True,
            ),
        ),
    ]
